### ISSUE TITLE
Events need sample code

### ISSUE THREAD

**Issue by ghost** [4screens/brightcove-player-cordova-plugin#6]
Trying to run the document event listeners, but it is unclear how I am supposed to run the functions in my controller. I have tried brightcovePlayer.show() by itself with no success and also, as it notes that they are run on the window, I have also tried window.brightcovePlayer.show() with no success. An example of usage will prove very useful.

**Comment by kostkobv** [comment]
```
window.addEventListener('brightcovePlayer.show', function(event){
  //your code
});
```
